# Convert a 1-D array into a 2-D array with 3 rows.

In [1]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8])
arr=arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Replace all odd numbers in the given array with -1

In [2]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
for i in range(arr.size):
    if arr[i]%2!=0:
        arr[i]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Find the positions of elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

In [3]:
import numpy as np

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21,  7,  3, 45, 10, 29, 55,  4, 37, 18])

a = np.where(x > y)[0].tolist()   
b = np.where(x == y)[0].tolist()  

print(a, end=',')
print(b, end=',')


[1, 2, 4, 5, 6, 7, 8, 9],[0],

# Extract the first four columns of this 2-D array

In [4]:
import numpy as np
a= np.arange(100).reshape(5,-1)
print(a[:a.size,0:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


# Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)

In [11]:
from numpy import random
x=random.randint(30,41,10)
print(x)

[35 40 39 30 35 30 31 30 37 32]


# Consider the following matrices : A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3)) Write a python program to perform the following using Numeric Python (numpy). 
i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
iii) Product of two matrices A and B, and print the resultant matrix D
iv) Sort the elements of resultant matrix C and print the resultant Matrix E.
v) Transpose the Matrix E and print the result

In [12]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

B = np.array([[7, 8, 10],
              [4, 5, 6],
              [1, 2, 3]])

C = A + B
E = A - B

print("Matrix C (A + B):\n", C)
print("\nMatrix E (A - B):\n", E)

sum_A = np.sum(A)
sum_columns_B = np.sum(B, axis=0)  
sum_rows_C = np.sum(C, axis=1)    

print("\nSum of all elements of matrix A:", sum_A)
print("Sum of each column of matrix B:", sum_columns_B)
print("Sum of each row of matrix C:", sum_rows_C)

D = np.dot(A, B)
print("\nMatrix D (A * B):\n", D)

E = np.sort(C, axis=None).reshape(C.shape)
print("\nMatrix E (sorted elements of matrix C):\n", E)

E_transposed = E.T
print("\nTranspose of matrix E:\n", E_transposed)


Matrix C (A + B):
 [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

Matrix E (A - B):
 [[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

Sum of all elements of matrix A: 46
Sum of each column of matrix B: [12 15 19]
Sum of each row of matrix C: [31 30 31]

Matrix D (A * B):
 [[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

Matrix E (sorted elements of matrix C):
 [[ 8  8  8]
 [10 10 10]
 [12 13 13]]

Transpose of matrix E:
 [[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
